// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTodo struct {
	UserID string `json:"user_id"`
	Task   string `json:"task"`
}

type NewUser struct {
	Username string  `json:"username"`
	Password *string `json:"password,omitempty"`
}

type Query struct {
}

type Todo struct {
	TodoID string `json:"todo_id"`
	UserID string `json:"user_id"`
	Task   string `json:"task"`
}

type User struct {
	UserID   string `json:"user_id"`
	Username string `json:"username"`
	Password string `json:"password"`
}
